---
# tasks file for sample-apache
- name: install httpd and firewalld
  yum:
    name:
      - httpd
      - firewalld
    state: latest

- name: enable httpd
  service:
      name: httpd
      state: started
      enabled: true

- name: enable firewall
  service:
      name: firewalld
      state: started

- name: allow firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

- name: populate index
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart

