---
- name: add users
  hosts: all
  become: yes
  vars_files:
    - userlist.yml
    - lock.yml

  tasks:
    - name: create devops group
      group:
        name: devops
      when: inventory_hostname in groups['dev']

    - name: create managers group
      group:
        name: managers
      when: inventory_hostname in groups['proxy']

    - name: create users on dev
      user:
        name: "{{ item.username }}"
        groups: devops
        password: "{{ pw_dev | password_hash('sha512') }}"
      loop: "{{ users }}"
      when:
        - inventory_hostname in groups['dev']
        - item.job == 'developer'

    - name: create users on proxy
      user:
        name: "{{ item.username }}"
        group: managers
        password: "{{ pw_mgr | password_hash('sha512') }}"
      loop: "{{ users }}"
      when:
        - inventory_hostname in groups['proxy']
        - item.job == 'manager'

